version: '3'
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
  nginx-proxy:
      image: jwilder/nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db_data:
